spring.application.name=ClimateViewer

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/ClimateViewer
spring.datasource.username=postgres
spring.datasource.password=admin

# ===============================
# JPA (aunque no lo usen, que no rompa)
# ===============================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
jwt.secret=MI_CLAVE_SECRETA_SUPER_SEGURA_384_ALGO_XYZ1234567890
jwt.expiration=3600000
jwt.refreshExpiration=86400000

# ===============================
# SERVER
# ===============================
server.port=8080
spring.session.store-type=none
